version: '3.8'

services:
  redis:
    image: "redis:5.0.4-stretch"
    volumes:
      - "redis:/data"
  web:
    build: ./app
    depends_on:
      - redis
      - db
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env
  beat:
    build: ./app
    depends_on:
      - redis
      - db
    command: python -m celery -A r_networking_ping  beat
    volumes:
      - ./app/:/usr/src/app/
    env_file:
      - ./.env
  worker:
    build: ./app
    depends_on:
      - redis
      - db
    command: python -m celery -A r_networking_ping  worker
    volumes:
      - ./app/:/usr/src/app/
    env_file:
      - ./.env
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
#    environment:
#      - POSTGRES_USER=hello_django
#      - POSTGRES_PASSWORD=hello_django
#      - POSTGRES_DB=hello_django_dev
    env_file:
      - ./.env.db

volumes:
  postgres_data:
  redis: {}