# Generated by Django 4.1.4 on 2022-12-08 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reachability', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='latency',
            new_name='avg_rtt',
        ),
        migrations.RenameField(
            model_name='test',
            old_name='status',
            new_name='is_alive',
        ),
        migrations.AddField(
            model_name='test',
            name='max_rtt',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='min_rtt',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='packet_loss',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='packets_received',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='packets_sent',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
