# Generated by Django 4.1.4 on 2026-02-27 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reachability', '0002_rename_latency_test_avg_rtt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='trace_mode',
            field=models.CharField(choices=[('always', 'Every probe'), ('on_fail', 'Only when ping fails')], default='on_fail', max_length=16),
        ),
        migrations.AddField(
            model_name='test',
            name='trace_attempted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='test',
            name='trace_output',
            field=models.TextField(blank=True, default=''),
        ),
    ]
